apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379  # The port on which Redis will be exposed
      targetPort: 6379  # The port in the container
  type: ClusterIP  # Internal access to Redis within the cluster
