apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel
  template:
    metadata:
      labels:
        app: keel
    spec:
      containers:
        - name: keel
          image: keelhq/keel:latest
          env:
            - name: KEEL_WEBHOOK_TOKEN
              value: "your-webhook-token" # Change this to a secure token
          ports:
            - containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: keel
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    app: keel
