apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keel-clusterrole
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["*"]      # Access all resources in the "apps" API group
    verbs: ["list", "get", "create", "update", "patch", "delete", "watch"]