apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keel-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: keel
    namespace: default
roleRef:
  kind: ClusterRole
  name: keel-clusterrole
  apiGroup: rbac.authorization.k8s.io
