apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keel-clusterrole
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["list", "watch"]