apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 86-105-246-107.haip.transip.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taggrs-dashboard
                port:
                  number: 80

