apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taggrs-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Custom-Header "HelloWorld";
spec:
  rules:
  - host: dashboard.taggrs.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: taggrs-dashboard-service
            namespace: default
            port:
              number: 80
