apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Steven4Hooisma/repo1.git
    targetRevision: main
    path: ./apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true