apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 16dag16e/taggrs-dashboard:~acceptance-0.1
spec:
  project: default
  source:
    repoURL: https://github.com/Steven4Hooisma/gitops.git
    targetRevision: main
    path: ./apps/dashboard
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true