apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: '69.2.4'  # Use a valid release version of the Prometheus Helm chart
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            replicas: 2
            serviceMonitorSelector: {}
            retention: 15d
        alertmanager:
          alertmanagerSpec:
            replicas: 2
        grafana:
          enabled: true
          adminPassword: "admin"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
