apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
        - name: cert-manager
          image: quay.io/jetstack/cert-manager-controller:v1.9.1
          args:
            - "--v=2"
            - "--cluster-resource-lifecycle=validate"
            - "--leader-election-namespace=kube-system"
          volumeMounts:
            - name: webhook-tls
              mountPath: /etc/cert-manager-webhook/tls
              readOnly: true
      volumes:
        - name: webhook-tls
          secret:
            secretName: cert-manager-webhook-tls
