apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-dev
  labels:
    app: cert-manager-dev
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: cert-manager-dev
  template:
    metadata:
      labels:
        app: cert-manager-dev
    spec:
      containers:
        - name: cert-manager-dev
          image: cert-manager:latest  # Change this to your image
